# Generated by Django 6.0.6 on 2026-07-23 00:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_google_event_id'),
        ('rooms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['date', 'status'], name='bookings_bo_date_d1c66f_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['room', 'date', 'status'], name='bookings_bo_room_id_ff4390_idx'),
        ),
    ]
