# Generated by Django 6.0.6 on 2026-07-22 04:16

import navigation.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SharedLocation',
            fields=[
                ('id', models.CharField(default=navigation.models.generate_share_id, editable=False, max_length=8, primary_key=True, serialize=False)),
                ('node_id', models.CharField(max_length=64)),
                ('building', models.CharField(max_length=64)),
                ('floor', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
